# Generated by Django 5.0.2 on 2025-08-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lable', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Location_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(upload_to='Location_images/')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('MetaTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('MetaDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('MetaKeywords', models.CharField(blank=True, max_length=100, null=True)),
                ('MetaUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('MetaCanonical', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationpage', to='hiteshApi.location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('About', models.TextField()),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Tag', models.CharField(max_length=50)),
                ('KeyFeatures', models.JSONField(default=list, help_text=' json format ["feature1","feature2"]')),
                ('NoOfReviews', models.IntegerField()),
                ('Specification', models.JSONField(default=list, help_text='json format [\n{"label": "Roller Size",\n"value": "127 x 63mm (5" x 2.5")"\n}\n]')),
                ('Application', models.JSONField(default=list, help_text='json format ["Jewelry sheet rolling","Wire rolling and reduction","Craft and custom metal forming"]')),
                ('TechnicalAdvantage', models.JSONField(default=list, help_text='json format ["Compact footprint","Minimal maintenance required"]')),
                ('RelatedProducts', models.ManyToManyField(blank=True, to='hiteshApi.product')),
                ('ProductType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiteshApi.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('KeyPoints', models.JSONField()),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Description', to='hiteshApi.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='product_images/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='hiteshApi.product')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hiteshApi.state'),
        ),
    ]
