# Generated by Django 5.0.2 on 2025-08-27 08:10

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('image_sq', models.ImageField(upload_to='blog/images')),
                ('image_hr', models.ImageField(upload_to='blog/images')),
                ('discription', models.TextField(default='')),
                ('text', django_quill.fields.QuillField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
