# Generated by Django 5.0.2 on 2025-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='product_hero/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
