# Generated by Django 5.0.2 on 2025-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0003_product_image_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='OrignamPrice',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='Sku',
            field=models.CharField(default='', max_length=200),
        ),
    ]
