# Generated by Django 5.0.2 on 2025-08-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0004_product_model_product_orignamprice_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='OrignamPrice',
            new_name='OrignalPrice',
        ),
    ]
