# Generated by Django 5.0.2 on 2025-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0005_rename_orignamprice_product_orignalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Shipping',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='Warranty',
            field=models.CharField(default='', max_length=200),
        ),
    ]
