# Generated by Django 5.0.2 on 2025-08-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0006_product_shipping_product_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('index', models.IntegerField(default=99)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('index', models.IntegerField(default=99)),
                ('ProductType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiteshApi.producttype')),
            ],
        ),
    ]
