# Generated by Django 5.0.2 on 2025-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0007_heroimages_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
