# Generated by Django 5.0.2 on 2025-08-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0009_clientlogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpage',
            old_name='Title',
            new_name='Heading',
        ),
        migrations.RenameField(
            model_name='locationpage',
            old_name='BannerImage',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='Description',
        ),
        migrations.AddField(
            model_name='locationpage',
            name='BottomParagraph',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='SubHeading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='TopParagraph',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.ImageField(upload_to='page_banners/')),
                ('index', models.IntegerField(default=99)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='hiteshApi.locationpage')),
            ],
        ),
    ]
