# Generated by Django 5.0.2 on 2025-09-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiteshApi', '0010_rename_title_locationpage_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='homeVideo/videos/')),
                ('fallback', models.ImageField(blank=True, null=True, upload_to='homeVideo/fallback/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBroucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='brouchers/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Broucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiteshApi.productbroucher'),
        ),
    ]
